using System;
using System.Collections.Generic;
using System.Text;
using Project0.app;
using Xunit;

namespace UnitTesting
{
    public class ConsoleFunctionality
    {
        readonly AutoGeneratedProgram testcon = new AutoGeneratedProgram();

        [Theory]
        [InlineData ('a','c','4',2,'z',' ','e')]
        public void _ValidScreenChoice(params char[] choices)
        {

          //  foreach (var x in choices)
                //Assert.True(choices.getscreenselection());
        }
    }
}
